// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jloxszzdrdnuqfrijhjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsb3hzenpkcmRudXFmcmlqaGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTIzNzcsImV4cCI6MjA2OTU2ODM3N30.myvZoyzvwrE2jPrYjMeTifNvEyn0jJS7x71LXTmmegs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});